### ISSUE TITLE
Single-page manifests

### ISSUE THREAD

**Issue by graft** [mountetna/timur#167]
When you edit a manifest, currently the manifest is separated into elements, e.g. "@element = some expression". This gets sent to the server as a list of [ 'element', 'some expression' ] pairs to be computed.

However, this separation is not required and is really kind of a pain in the ass in terms of editing; it creates a lot of interface components unnecessarily and makes it difficult to reorder elements.

Since the execution order matters (elements may refer to the values of previously computed elements), we should instead write a single script like this:

    @var1 = some expression

    # some comments here
    @var2 = some other expression

This can be edited in a single script block and saved to a single text field in the database; the lexer/parser can take care of the rest.

Requirements:

1. Change the database so it stores scripts as a single text blob rather than a list-of-element-pairs. Update existing scripts.

2. Change the manifest view/edit code so there is only a single script block to edit.

3. Change the lexer/parser so it parses @var1 = expression correctly.

**Comment by jasondcater** [comment]
This was being covered by the branch `emark-manifests-167`. This item needs more design work.
