### ISSUE TITLE
Restyle the Identifier Search Component

### ISSUE THREAD

**Issue by jasondcater** [mountetna/timur#185]
As part of the general UI/UX clean up we need to do a simple restyling of the Identifier Search Component. The basic functionality should not change.

1. Normalize colors.
2. Remove rounded edges.
3. Remove nested scroll bars.

**Comment by graft** [comment]
I think removing the nested scrollbars significantly changes the behavior and more thought is needed before changing the design.  For example, now I can type CRC and quickly navigate to the CRC patient I want without having to scroll past all of the CRC samples. Removing the nesting would make this more difficult, perhaps ruining the utility of this component as a 'quick navigation'. If we get rid of the nesting we should do something else to make it easier to navigate.

**Comment by jasondcater** [comment]
There will be some form of nesting. However,  interior scroll bars will be removed. The replacement functionality will be based upon need which has to be given study. The current state of the component will be our  "A" and the modified component (Eleanor is building) will be the "B".

**Comment by jasondcater** [comment]
Remove the search spy glass and insert "quick search" as the placeholder (light grey, italic).

**Comment by graft** [comment]
Done a bit in #238, calling this ok for the moment.
