### ISSUE TITLE
Restyle the Navigation Component.

### ISSUE THREAD

**Issue by jasondcater** [mountetna/timur#186]
This is another part of the general UI/UX clean up and restyling. This should be done after issue #185 

The functionality should remain the same. Coloring and fonts should be normalized with the Identifier Search.

**Comment by jasondcater** [comment]
@eleanormark 

![screenshot](https://user-images.githubusercontent.com/6519071/38016562-3eaa8bc8-3224-11e8-83d3-81b720516a94.jpg)

Attached is a screen shot from timur2 that shows the direction of the nav look. Don't worry about styling the area below the navigation. You can look in the timur2 repo to extract the scss.

The links to the the other sections of the site should be fairly simple in style.

Make sure this is branched from master and I'll inspect the work remotely.

**Comment by jasondcater** [comment]
Integrate the loading image, error handling, and messaging.

**Comment by graft** [comment]
Did some nav restyling in #238. Error handling remains woeful.
