### ISSUE TITLE
Extract shared UI components (with Metis) into separate NPM package

### ISSUE THREAD

**Issue by coleshaw** [mountetna/timur#253]
To achieve mountetna/planning#30 I'm just copying the Metis upload code over. But it would be nice to extract those kinds of things into a shared library that we can host on NPM.

**Comment by graft** [comment]
Yes! for a long time I have felt that we need an etna npm package (maybe this should be an etna issue?) alongside the etna ruby gem, where we might keep common JSX components, routers, etc., in addition to this upload client stuff. Would be nice to extract this ASAP before the upload stuff starts to diverge.

**Comment by coleshaw** [comment]
I'm trying to wrap my head around the Metis upload stuff right now ... will see if I can extract it into a separate repo and have it still work in both contexts. Seems like there are quite a few components involved.
