### ISSUE TITLE
Patient table .tsv to Excel in Windows loses sample ID number

### ISSUE THREAD

**Issue by meghanz** [mountetna/timur#42]
From a partner:

"I just downloaded the tsv for the patient table for the IPICRC samples for TIMUR.
 
A strange thing happened when I imported it into excel.
For the “sample” column (column 13) the names are IPIHNSC###
 
It could be due to the split rows in that column. The conversion to windows and Excel can’t handle it.
Is this something you could address, or can you suggest a workaround (using a MAC isn’t an option unfortunately!)"

**Comment by graft** [comment]
I think there is a problem with certain notes fields having newline characters in them that makes broken TSVs. However, this does not appear to be that problem. I went to the search page, selected 'patient' and did this search: 'ipi_number~CRC' - clicking TSV produced a TSV of patient samples, so perhaps the search was incorrect?

**Comment by dabrau** [comment]
It is probably due to the comma for the values in the sample column. Maybe it can't figure out if its CSV or TSV when you open it. If the windows version has an option to import as TSV explicitly do that. My suggestion would be to use Google Sheets as a work around.

**Comment by meghanz** [comment]
Changing the search query worked. The broken query was:

Searched for “experiment~colorectal”. Partner tried that search again just now and the same error happened: the initial table in TIMUR looks correct but when downloaded it has the HNSC refs.

**Comment by graft** [comment]
Closing as this seems to work and is probably fixed in the new version anyway.
